language: rust
cache: cargo
rust:
  - nightly
  - stable
  - beta
os:
  - linux
  - osx

before_script:
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - env

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  # Format only on nightly, since that is where rustfmt-nightly compiles
  - if [ "${TRAVIS_RUST_VERSION}" = "nightly" ] && [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      export LD_LIBRARY_PATH=$(rustc --print sysroot)/lib:$LD_LIBRARY_PATH
      && ./format.sh --write-mode=diff;
    else
      echo "Not checking formatting on this build";
    fi

notifications:
  email:
    on_success: never
    on_failure: never
