sudo: false
env:
  global:
    - MACOSX_DEPLOYMENT_TARGET="10.7"

matrix:
  include:
    - language: node_js
      node_js: '8'
      cache: yarn

      install:
        - yarn install

        # FIXME: Flow throws error for optional dependencies
        # missing from node_modules on unsupported platforms
        # see: https://github.com/facebook/flow/issues/4171
        - OPTIONAL_DEPS=('nseventmonitor' 'windows-security');
          for MODULE in ${OPTIONAL_DEPS[@]}; do
            FILE="node_modules/$MODULE/index.js";
            if [ ! -f $FILE ]; then
              echo "Installing a stub for $MODULE..";
              mkdir -p `dirname $FILE`;
              echo "module.exports = {};" > $FILE;
            fi
          done
      before_script:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
      script:
        - yarn run lint
        - yarn run flow
        - yarn test


    # Backend macOS
    - language: rust
      rust: stable
      os: osx
      cache: cargo

      before_script: &rust_before_script
        - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
        - env
      script: &rust_script
        - cargo build --verbose
        - cargo test --verbose

    # Backend Linux
    - language: rust
      rust: nightly
      os: linux
      cache: cargo
      before_script: *rust_before_script
      script:
        - cargo build --verbose
        - cargo test --verbose
        # Install and run rustfmt on nightly only until rustfmt.toml settings are stabilized.
        - rustup component add rustfmt-preview
        - rustfmt --version
        - cargo fmt -- --write-mode=diff

    - language: rust
      rust: beta
      os: linux
      cache: cargo
      before_script: *rust_before_script
      script: *rust_script

    - language: rust
      rust: stable
      os: linux
      cache: cargo
      before_script: *rust_before_script
      script: *rust_script


notifications:
  email:
    on_success: never
    on_failure: never
