language: rust
cache: cargo
rust:
  - stable
  - nightly
os:
  - linux
  - osx

before_script:
  - (cargo install --force rustfmt || true)
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - rustfmt --version

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --write-mode=diff

notifications:
  email:
    on_success: never
    on_failure: never
