language: rust
cache:
  cargo: true
  directories:
    - $HOME/build-deps

rust:
  - stable
  - nightly
os:
  - linux
  - osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx"   ]]; then mkdir -p $HOME/.local/bin && ln -s /usr/local/bin/greadlink $HOME/.local/bin/readlink ; fi
  - $(./build-deps/install-build-deps.sh $HOME/build-deps)
  - (cargo install rustfmt || true)
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - rustfmt --version
  - env

script:
    ## zmq-sys caches the location of `libzmq`, if that location ever changes e.g.
    ## if the version changes we will get into trouble. This rm will make us
    ## rebuild it every time instead
  - rm -rf target/debug/build/zmq*

  - cargo build --verbose
  - cargo test --all --verbose
  - find . -iname "*.rs" -not -path "*/target/*" -print0 | xargs -0 -n1 rustfmt --write-mode=diff

notifications:
  email:
    on_success: never
    on_failure: never
