language: rust
cache: cargo
rust:
  - stable
  - nightly
os:
  - linux
  - osx
env:
  global:
    - RUST_TEST_THREADS=1

before_script:
  - (cargo install rustfmt || true)
  - export PATH=$HOME/.local/bin:$PATH
  - export PATH=$HOME/.cargo/bin:$PATH

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo fmt -- --write-mode=diff
notifications:
  email:
    on_success: never
    on_failure: never
