language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
os:
  - linux
  - osx

before_script:
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - env

script:
  - cargo build --all --verbose
  - cargo test --all --verbose
  - ./format.sh --write-mode=diff

notifications:
  email:
    on_success: never
    on_failure: never
