language: rust
cache: cargo
rust:
  - stable
  - nightly
os:
  - linux
  - osx

before_script:
  - (cargo install rustfmt || true)
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - rustfmt --version

script:
  - cargo build --verbose
  - cargo test --all --verbose
  - find src/ tests/ benches/ talpid_* -iname "*.rs" -print0 | xargs -0 -n1 rustfmt --write-mode=diff

notifications:
  email:
    on_success: never
    on_failure: never
