sudo: false

language: node_js

node_js:
  - '8'
  - '7'
  - '6'

before_script:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

cache:
    yarn: true

install:
  - yarn install

  # FIXME: Flow throws error for optional dependencies
  # missing from node_modules on unsupported platforms
  # see: https://github.com/facebook/flow/issues/4171
  - NSEVENTMON_INDEX_JS=node_modules/nseventmonitor/index.js;
    if [ ! -f $NSEVENTMON_INDEX_JS ]; then
      echo "Installing a stub for NSEventMonitor..";
      mkdir -p `dirname $NSEVENTMON_INDEX_JS`;
      echo "module.exports = {};" > $NSEVENTMON_INDEX_JS;
    fi

script:
  - yarn run lint
  - yarn run flow
  - yarn test
