sudo: false

git:
  submodules: false

before_install:
  - git submodule update --init

matrix:
  include:
    # GUI - Electron
    - language: node_js
      node_js: '8'
      cache: npm
      install:
        - cd gui
        - npm install
      before_script:
        - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
      script:
        - npm run check-format
        - npm run lint
        - npm run build
        - npm test


    # Daemon - macOS
    - language: rust
      rust: stable
      os: osx
      before_script: &rust_before_script
        - source env.sh
        - env
      script: &rust_script
        - cargo build --verbose
        - cargo test --verbose

    # Daemon - Linux
    - language: rust
      rust: nightly
      os: linux
      addons: &rust_linux_addons
        apt:
         sources:
          - sourceline: "ppa:jonathonf/gcc-7.3"
            key_url: "https://pgp.key-server.io/download/0xE03043828C3FF4BB"
         packages:
          - binutils
          - libdbus-1-dev
      before_script: *rust_before_script
      script:
        - cargo build --verbose
        - cargo test --verbose
        # Install and run rustfmt on nightly only until rustfmt.toml settings are stabilized.
        - rustup component add rustfmt-preview
        - cargo fmt --version || true
        - cargo fmt -- --check --unstable-features

    - language: rust
      rust: beta
      os: linux
      addons: *rust_linux_addons
      before_script: *rust_before_script
      script: *rust_script

    - language: rust
      rust: stable
      os: linux
      addons: *rust_linux_addons
      before_script: *rust_before_script
      script: *rust_script


notifications:
  email:
    on_success: never
    on_failure: never
