[package]
name = "talpid_core"
version = "0.0.0"
authors = ["Linus Färnstrand <linus@mullvad.net>"]

[dependencies]
clonablechild = "0.1"

[dev-dependencies]
assert_matches = "1.0"

[workspace]
members = ["talpid_openvpn_plugin", "talpid_cli"]
