[package]
name = "talpid_core"
version = "0.0.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Core backend functionality of the Mullvad VPN client"

[dependencies]
clonablechild = "0.1"
error-chain = "0.8"

[dependencies.talpid_ipc]
path = "talpid_ipc"

[target.'cfg(not(windows))'.dependencies]
zmq = "0.8"

[dev-dependencies]
assert_matches = "1.0"

[workspace]
members = ["talpid_openvpn_plugin", "talpid_cli", "talpid_ipc"]
