[workspace]
members = [
    "mullvad-daemon",
    "mullvad-cli",
    "mullvad-ipc-client",
    "mullvad-metadata",
    "mullvad-types",
    "mullvad-rpc",
    "talpid-openvpn-plugin",
    "talpid-core",
    "talpid-ipc",
]
