[package]
name = "talpid_core"
version = "0.0.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Core backend functionality of the Mullvad VPN client"

[dependencies]
duct = "0.8"
error-chain = "0.10"
log = "0.3"
jsonrpc-core = { git = "https://github.com/faern/jsonrpc", branch = "bind-zero" }
jsonrpc-macros = { git = "https://github.com/faern/jsonrpc", branch = "bind-zero" }

[dependencies.talpid_ipc]
path = "../talpid_ipc"

[dependencies.openvpn_ffi]
path = "../openvpn_ffi"

[dev-dependencies]
assert_matches = "1.0"
