[package]
name = "talpid_core"
version = "0.0.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Core backend functionality of the Mullvad VPN client"

[dependencies]
clonablechild = "0.1"
error-chain = "0.10"
log = "0.3"

[dependencies.talpid_ipc]
path = "../talpid_ipc"

[dependencies.openvpn_ffi]
path = "../openvpn_ffi"

[dev-dependencies]
assert_matches = "1.0"
