[package]
name = "mullvad-types"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>"]

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde_derive = "1.0"
serde = "1.0"
