[package]
name = "mullvad-types"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "Common base data structures for Mullvad VPN client"
license = "GPL-3.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde_derive = "1.0"
serde = "1.0"
serde_json = "1.0"
error-chain = "0.12"
log = "0.4"

talpid-types = { path = "../talpid-types" }
mullvad-paths = { path = "../mullvad-paths" }
