[package]
name = "mullvad-types"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>"]
license = "GPL-3.0"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde_derive = "1.0"
serde = "1.0"
