[package]
name = "talpid_cli"
version = "0.0.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Run Talpid easily from the command line"

[dependencies]
clap = "2.20"
error-chain = "0.10"
log = "0.3"
env_logger = "0.4"

[dependencies.talpid_core]
path = "../talpid_core"
