[package]
name = "talpid_ipc"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "IPC client and server for talpid"

[dependencies]
error-chain = "0.10"
serde = "0.9"
serde_json = "0.9"
log = "0.3"
jsonrpc-core = { git = "https://github.com/faern/jsonrpc", branch = "bind-zero" }
jsonrpc-ws-server = { git = "https://github.com/faern/jsonrpc", branch = "bind-zero" }

[target.'cfg(not(windows))'.dependencies]
zmq = "0.8"

[dev-dependencies]
assert_matches = "1.0"
