[package]
name = "mullvad_daemon"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Mullvad VPN backend daemon. Runs and controls the VPN tunnels."

[[bin]]
name = "mullvadd"

[dependencies]
chrono = "0.4"
clap = "2.25"
error-chain = "0.10"
fern = "0.4"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc" }
uuid = { version = "0.5", features = ["v4"] }
lazy_static = "0.2"

mullvad_types = { path = "../mullvad_types" }
talpid_core = { path = "../talpid_core" }
talpid_ipc = { path = "../talpid_ipc" }

[target.'cfg(unix)'.dependencies]
simple-signal = "1.1"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.0"

[dev-dependencies]
assert_matches = "1.0"
