[package]
name = "mullvad_daemon"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "The meat of Mullvad, the core if you wish"

[dependencies]
error-chain = "0.10"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
env_logger = "0.4"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-pubsub = { git = "https://github.com/paritytech/jsonrpc" }
jsonrpc-ws-server = { git = "https://github.com/paritytech/jsonrpc" }
uuid = { version = "0.5", features = ["v4"] }
lazy_static = "0.2"

talpid_core = { path = "../talpid_core" }
talpid_ipc = { path = "../talpid_ipc" }

[target.'cfg(unix)'.dependencies]
simple-signal = "1.1"

[target.'cfg(windows)'.dependencies]
ctrlc = "3.0"

[dev-dependencies]
assert_matches = "1.0"
