[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
description = "Privacy preserving and secure VPN client library"
license = "GPL-3.0"

[dependencies]
atty = "0.2"
duct = "0.10"
error-chain = "0.12"
ipnetwork = "0.13"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc", tag = "v8.0.1" }
lazy_static = "1.0"
libc = "0.2.20"
log = "0.4"
openvpn-plugin = { version = "0.3", features = ["serde"] }
os_pipe = "0.6"
shell-escape = "0.1"
uuid = { version = "0.6", features = ["v4"] }

talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }

[target.'cfg(target_os = "linux")'.dependencies]
notify = "4.0"
resolv-conf = "0.6.1"
nftnl = { git = "https://github.com/mullvad/nftnl-rs", features = ["nftnl-1-1-0"] }
mnl = { git = "https://github.com/mullvad/mnl-rs", features = ["mnl-1-0-4"] }

[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.2"
system-configuration = "0.1"
core-foundation = "0.5"
tokio-core = "0.1"

[target.'cfg(windows)'.dependencies]
widestring = "0.3"

[dev-dependencies]
tempfile = "3.0"
