[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
description = "Core backend functionality of the Mullvad VPN client"
license = "GPL-3.0"

[dependencies]
duct = "0.9.1"
error-chain = "0.11"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", tag = "v7.1.1" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc", tag = "v7.1.1" }
lazy_static = "1.0"
log = "0.3"
uuid = { version = "0.5", features = ["v4"] }
shell-escape = "0.1"

openvpn-plugin = { version = "0.3", features = ["serde"] }
talpid-ipc = { path = "../talpid-ipc" }
talpid-types = { path = "../talpid-types" }

[target.'cfg(unix)'.dependencies]
libc = "0.2.20"

[target.'cfg(target_os = "macos")'.dependencies]
pfctl = "0.1"
system-configuration = { git = "https://github.com/mullvad/system-configuration-rs", version = "0.1.0" }
core-foundation = "0.4.6"
tokio-core = "0.1"
