[package]
name = "talpid-core"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Core backend functionality of the Mullvad VPN client"

[dependencies]
duct = "0.9.1"
error-chain = "0.11"
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", tag = "v7.1.0" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc", tag = "v7.1.0" }
lazy_static = "0.2"
log = "0.3"
uuid = { version = "0.5", features = ["v4"] }

openvpn-plugin = { version = "0.2", features = ["serialize"] }
talpid-ipc = { path = "../talpid-ipc" }

[target.'cfg(unix)'.dependencies]
libc = "0.2.20"

[target.'cfg(target_os = "macos")'.dependencies]
pfctl = { git = "https://github.com/mullvad/pfctl-rs.git" }

[dev-dependencies]
assert_matches = "1.0"
