[package]
name = "talpid_openvpn_plugin"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "OpenVPN shared library plugin for relaying OpenVPN events to talpid_core"

[lib]
crate-type = ["dylib"]

[dependencies]
error-chain = "0.8"
log = "0.3"
env_logger = "0.4"

[dependencies.talpid_ipc]
path = "../talpid_ipc"

[dev-dependencies]
assert_matches = "1.0"
