[package]
name = "talpid_openvpn_plugin"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>"]

[lib]
crate-type = ["dylib"]

[dependencies]
lazy_static = "0.2"
error-chain = "0.8"

[dev-dependencies]
assert_matches = "1.0"
