[package]
name = "socket-relay"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>"]
description = "A relay for bidirectional sockets. Listens to one address and relays all traffic to another."
license = "MIT/Apache-2.0"
keywords = ["socket", "network", "forward", "relay", "proxy"]
categories = ["network-programming", "asynchronous"]

[dependencies]
env_logger = "0.4.3"
error-chain = "0.11"
futures = "0.1.15"
log = "0.3"
tokio-core = "0.1"
tokio-timer = "0.1"
