[package]
name = "mullvad-cli"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Run Talpid easily from the command line"

[[bin]]
name = "mullvad"
path = "src/main.rs"

[dependencies]
clap = "2.20"
error-chain = "0.11"
lazy_static = "0.2"
log = "0.3"
env_logger = "0.4"
serde = "1.0"
serde_json = "1.0"

mullvad-types = { path = "../mullvad-types" }
talpid-ipc = { path = "../talpid-ipc" }
