[package]
name = "mullvad-jni"
version = "0.1.0"
authors = ["Mullvad VPN <admin@mullvad.net>"]
description = "JNI interface for the Mullvad daemon"
license = "GPL-3.0"
edition = "2018"

[lib]
crate_type = ["cdylib"]

[dependencies]
err-derive = "0.1.5"
jni = "0.11"
lazy_static = "1"
log = "0.4"
log-panics = "2"
parking_lot = "0.8"

mullvad-daemon = { path = "../mullvad-daemon" }
mullvad-paths = { path = "../mullvad-paths" }
mullvad-types = { path = "../mullvad-types" }
talpid-types = { path = "../talpid-types" }
