[package]
name = "openvpn_ffi"
version = "0.1.0"
authors = ["Linus Färnstrand <linus@mullvad.net>", "Erik Larkö <erik@mullvad.net>"]
description = "Constants, enums and structs for interfacing with OpenVPN"

[dependencies]
error-chain = "0.8"

[dev-dependencies]
assert_matches = "1.0"
