[package]
name = "mullvad-problem-report"
version = "2018.2.0-beta1"
authors = ["Mullvad VPN <admin@mullvad.net>", "Linus Färnstrand <linus@mullvad.net>", "Andrej Mihajlov <and@mullvad.net>"]
description = "Collect Mullvad VPN logs into a report and send it to support"
license = "GPL-3.0"

[[bin]]
name = "problem-report"
path = "src/main.rs"

[dependencies]
clap = "2.25"
error-chain = "0.12"
lazy_static = "1.0"
regex = "1.0"

mullvad-paths = { path = "../mullvad-paths" }
mullvad-rpc = { path = "../mullvad-rpc" }
